// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class subscribemail_added_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subscribemail_added_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202203110301182_subscribemail_added_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
